services:
  productservice:
    build: product-service

  web:
    build: nginx
    ports:
      - "80:80"

  db:
    image: mysql
    command: "--init-file /data/application/init.sql"
    volumes:
      - ./db/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: products
